steps:
- name: 'ubuntu'
  args:
  - 'pwd'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'pull'
  - 'gradle:4.7.0-jdk10'
- name: 'gcr.io/cloud-builders/docker'
  dir: 'dist'
  args:
  - 'run'
  - '--rm'
  - '-v'
  - '/workspace/dist:/home/gradle/project'
  - '-w'
  - '/home/gradle/project'
  - 'gradle:4.7.0-jdk10'
  - 'gradle'
  - 'build'
  - '--debug'


#  args:
#  - 'build'
#  - '--build-arg'
#  - 'version=1.16.1'
#  - '-t'
#  - "eu.gcr.io/$PROJECT_ID/$REPO_NAME:latest"
#  - '.'
#
#images:
#- 'gcr.io/$PROJECT_ID/docker-compose:latest'