steps:
- name: 'ubuntu'
  args:
  - 'ls'
  - '-help'
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - 'https://Sebastien_Andre@bitbucket.org/Sebastien_Andre/mobylis-backend.git'
#- name: 'gcr.io/cloud-builders/docker'
#  args:
#  - 'pull'
#  - 'gradle:4.7.0-jdk10'
#- name: 'gcr.io/cloud-builders/docker'
#  dir: 'dist'
#  args:
#  - 'run'
#  - '--rm'
#  - '-v'
#  - '/workspace/dist:/home/gradle/project'
#  - '-w'
#  - '/home/gradle/project'
#  - 'gradle:4.7.0-jdk10'
#  - 'gradle'
#  - 'build'

#  args:
#  - 'build'
#  - '--build-arg'
#  - 'version=1.16.1'
#  - '-t'
#  - "eu.gcr.io/$PROJECT_ID/$REPO_NAME:latest"
#  - '.'
#
#images:
#- 'gcr.io/$PROJECT_ID/docker-compose:latest'