steps:
- name: 'ubuntu'
  args:
  - 'ls'
  - '-l'
- name: 'ubuntu'
  args:
  - 'chmod'
  - '-R'
  - '777'
  - '/workspace'
- name: 'ubuntu'
  args:
  - 'ls'
  - '-l'
#- name: 'gcr.io/cloud-builders/git'
#  args:
#  - 'clone'
#  - 'https://Sebastien_Andre@bitbucket.org/Sebastien_Andre/mobylis-backend.git'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'pull'
  - 'gradle:4.7.0-jdk10'
- name: 'gcr.io/cloud-builders/docker'
  env: ['GRADLE_HOME=/workspace', 'GRADLE_USER_HOME=/workspace']
  args:
  - 'run'
  - '--rm'
  - '-v'
  - '/workspace:/home/gradle/project'
  - '-w'
  - '/home/gradle/project'
  - 'gradle:4.7.0-jdk10'
  - 'gradle'
  - 'build'
  - '--info'

#images:
#- 'gcr.io/$PROJECT_ID/docker-compose:latest'