steps:
- name: 'ubuntu'
  args:
  - 'chmod'
  - '-R'
  - '777'
  - '/workspace'
#- name: 'gcr.io/cloud-builders/docker'
#  args:
#  - 'pull'
#  - 'gradle:4.7.0-jdk10'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'run'
  - '--rm'
  - '-v'
  - '/workspace:/home/gradle/project'
  - '-w'
  - '/home/gradle/project'
  - 'gradle:4.7.0-jdk10'
  - 'gradle'
  - 'build'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '.'
  - '-t'
  - 'gcr.io/$PROJECT_ID/mobylis-backend:latest'

images:
- 'gcr.io/$PROJECT_ID/mobylis-backend:latest'