steps:
- name: 'ubuntu'
  args:
  - 'chmod'
  - '-R'
  - '777'
  - '/workspace'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'pull'
  - 'gradle:4.7.0-jdk10'
  - '--cache-from'
- name: 'gcr.io/cloud-builders/docker'
  env: ['GRADLE_HOME=/workspace', 'GRADLE_USER_HOME=/workspace']
  args:
  - 'run'
  - '--rm'
  - '-v'
  - '/workspace:/home/gradle/project'
  - '-w'
  - '/home/gradle/project'
  - 'gradle:4.7.0-jdk10'
  - 'gradle'
  - 'build'
  - '--info'

#images:
#- 'gcr.io/$PROJECT_ID/docker-compose:latest'