server:
  port: 80

cloudinary:
  cloud-name: dqismn81g
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

---
##
# Profile: Local-swarm launched
##

spring:
  profiles: local-swarm

elasticsearch:
  scheme: http
  host: localhost
  port: 9200

logging.level:
    org.springframework.web: debug
    org.springframework.security: debug
---
##
# Profile: Prod (docker swarm)
##

spring:
  profiles: prod,production

elasticsearch:
  scheme: http
  host: 35.234.67.234
  port: 9200

