# H2 config
spring:
  h2:
    console:
      enabled: true
      path: /h2

# Datasource
spring.datasource:
  url: jdbc:h2:file:./src/main/database/mobylis
  username: sa
  password:
  driver-class-name: org.h2.Driver

# Server port
server:
  port: 9090