REPLACE INTO CATEGORY (ID, NAME) VALUES (1, 'DECKS');
REPLACE INTO CATEGORY (ID, NAME) VALUES (2, 'ACCESSORIES');
REPLACE INTO CATEGORY (ID, NAME) VALUES (3, 'ADJUSTABLE_DECKS');
REPLACE INTO CATEGORY (ID, NAME) VALUES (4, 'SEATS');