# H2 config
spring:
  profiles:
    active: local

# Server port
server:
  port: 9090

elasticsearch:
  portA: 9200
  portB: 9201
---
##
# Profile: Local
# DATABASE: H2
##
spring:
  profiles: local

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    show-sql: true
    generate-ddl: true

elasticsearch:
  scheme: http
  host: localhost
  port: 9200
---
##
# Profile: Development
# DATABASE: MYSQL - TEST
##
spring:
  profiles: dev,development

# Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${GOOGLE_CLOUD_PLATFORM_HOSTNAME}:3306/mobylis?useSSL=false
    username: mobylis-backend
    password: ${MYSQL_PASSWORD_FILE}

  jpa:
    show-sql: true
    generate-ddl: true

elasticsearch:
  scheme: http
  host: ${GOOGLE_CLOUD_PLATFORM_HOSTNAME}
  portA: 9200
---
##
# Profile: Test (docker swarm)
# DATABASE: MYSQL - TEST
##
spring:
  profiles: test,testing

# Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/mobylis?useSSL=false
    username: mobylis-backend
    password: ${MYSQL_PASSWORD_FILE}

  jpa:
    show-sql: true
    generate-ddl: false

elasticsearch:
  scheme: http
  host: elasticsearch
  port: 9200
---
##
# Profile: Prod (docker swarm)
# DATABASE: MYSQL - PROD
##
spring:
  profiles: prod,production

# Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/mobylis?useSSL=false
    username: mobylis-backend
    password: ${MYSQL_PASSWORD_FILE}
    name: mobylis

  jpa:
    show-sql: false
    generate-ddl: false

elasticsearch:
  scheme: http
  host: elasticsearch
  port: 9200