# H2 config
spring:
  profiles:
    active: dev

# Server port
server:
  port: 9090

---
##
# Profile: Local
# DATABASE: H2
##
spring:
  profiles: local

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
---
##
# Profile: Development
# DATABASE: MYSQL - TEST
##
spring:
  profiles: dev
# Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOSTNAME}:3306
    username: mobylis-backend
    password: ${MYSQL_PASSWORD_FILE}

---
##
# Profile: Test (docker swarm)
# DATABASE: MYSQL - TEST
##
spring:
  profiles: test
# Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306
    username: mobylis-backend
    password: ${MYSQL_PASSWORD_FILE}
---
##
# Profile: Prod (docker swarm)
# DATABASE: MYSQL - PROD
##
spring:
  profiles: prod

# Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306
    username: mobylis-backend
    password: ${MYSQL_PASSWORD_FILE}