# H2 config
spring:
  profiles:
    active: dev

# Server port
server:
  port: 9090

---
##
# Profile: Local
# DATABASE: H2
##
spring:
  profiles: local

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    show-sql: true
    generate-ddl: true
---
##
# Profile: Development
# DATABASE: MYSQL - TEST
##
spring:
  profiles: dev,development
# Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOSTNAME}:3306/mobylis?useSSL=false
    username: mobylis-backend
    password: ${MYSQL_PASSWORD_FILE}

  jpa:
    show-sql: true
    generate-ddl: true
---
##
# Profile: Test (docker swarm)
# DATABASE: MYSQL - TEST
##
spring:
  profiles: test,testing
# Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/mobylis?useSSL=false
    username: mobylis-backend
    password: ${MYSQL_PASSWORD_FILE}

  jpa:
    show-sql: true
    generate-ddl: false
---
##
# Profile: Prod (docker swarm)
# DATABASE: MYSQL - PROD
##
spring:
  profiles: prod,production

# Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/mobylis?useSSL=false
    username: mobylis-backend
    password: ${MYSQL_PASSWORD_FILE}
    name: mobylis

  jpa:
    show-sql: false
    generate-ddl: false